### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by minijaham** [Chalapa13/WorldGuard#102]
19.04 00:04:44 [Server] Server thread/CRITICAL TypeError: "Argument 1 passed to Chalapa13\WorldGuard\WorldGuard::getRegionByPlayer() must be an instance of pocketmine\Player, instance of pocketmine\entity\object\PrimedTNT given, called in phar:///plugins/WorldGuard.phar/src/Chalapa13/WorldGuard/EventListener.php on line 372" (EXCEPTION) in "plugins/WorldGuard.phar/src/Chalapa13/WorldGuard/WorldGuard" at line 198
19.04 00:04:44 [Server] Server thread/DEBUG #0 plugins/WorldGuard.phar/src/Chalapa13/WorldGuard/EventListener(372): Chalapa13\WorldGuard\WorldGuard->getRegionByPlayer(object pocketmine\entity\object\PrimedTNT)
19.04 00:04:44 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/MethodEventExecutor(42): Chalapa13\WorldGuard\EventListener->onHurtByEntity(object pocketmine\event\entity\EntityDamageByEntityEvent)
19.04 00:04:44 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object Chalapa13\WorldGuard\EventListener, object pocketmine\event\entity\EntityDamageByEntityEvent)
19.04 00:04:44 [Server] Server thread/DEBUG #3 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent)
19.04 00:04:44 [Server] Server thread/DEBUG #4 src/pocketmine/entity/Entity(925): pocketmine\event\Event->call()
19.04 00:04:44 [Server] Server thread/DEBUG #5 src/pocketmine/entity/Living(545): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
19.04 00:04:44 [Server] Server thread/DEBUG #6 src/pocketmine/Player(3708): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
19.04 00:04:44 [Server] Server thread/DEBUG #7 src/pocketmine/level/Explosion(200): pocketmine\Player->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
19.04 00:04:44 [Server] Server thread/DEBUG #8 src/pocketmine/entity/object/PrimedTNT(112): pocketmine\level\Explosion->explodeB()
19.04 00:04:44 [Server] Server thread/DEBUG #9 src/pocketmine/entity/object/PrimedTNT(97): pocketmine\entity\object\PrimedTNT->explode()
19.04 00:04:44 [Server] Server thread/DEBUG #10 src/pocketmine/entity/Entity(1383): pocketmine\entity\object\PrimedTNT->entityBaseTick(integer 1)
19.04 00:04:44 [Server] Server thread/DEBUG #11 src/pocketmine/level/Level(844): pocketmine\entity\Entity->onUpdate(integer 3657)
19.04 00:04:44 [Server] Server thread/DEBUG #12 src/pocketmine/level/Level(777): pocketmine\level\Level->actuallyDoTick(integer 3657)
19.04 00:04:44 [Server] Server thread/DEBUG #13 src/pocketmine/Server(2256): pocketmine\level\Level->doTick(integer 3657)
19.04 00:04:44 [Server] Server thread/DEBUG #14 src/pocketmine/Server(2387): pocketmine\Server->checkTickUpdates(integer 3657, double 1587254684.5875)
19.04 00:04:44 [Server] Server thread/DEBUG #15 src/pocketmine/Server(2143): pocketmine\Server->tick()
19.04 00:04:44 [Server] Server thread/DEBUG #16 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
19.04 00:04:44 [Server] Server thread/DEBUG #17 src/pocketmine/Server(1584): pocketmine\Server->start()
19.04 00:04:44 [Server] Server thread/DEBUG #18 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /, string[55] /plugins/)
19.04 00:04:44 [Server] Server thread/DEBUG #19 src/pocketmine/PocketMine(296): pocketmine\server()
19.04 00:04:44 [Server] Server thread/DEBUG #20 (11): require(string[107] phar:///PMMP-Latest-Stable.phar/sr)
19.04 00:04:44 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump

Whenever I go to wild, this happens.

**Comment by awgybop1** [comment]
This bug has been fixed! :)

**Comment by minijaham** [comment]
Yay!
