### ISSUE TITLE
The entire server's pvp gets disabled

### ISSUE THREAD

**Issue by Johnsonk79** [Chalapa13/WorldGuard#103]
Using the latest build and pocket mine version, after running the server with the plugin, the entire server's PVP gets disabled, including the regions that had PVP enabled, here's a [short clip](https://streamable.com/5ensni)

Please fix it, Thanks a lot!

**Comment by awgybop1** [comment]
Hello! This bug cannot be reproduced by me, inside of a region with PvP enabled, inside of the global region with PvP enabled, or inside of no region.
Please PM me on Discord for further help :) - I am @AustinG
