### ISSUE TITLE
Effect -> Possible way to fix

### ISSUE THREAD

**Issue by suerion** [Chalapa13/WorldGuard#104]
our dev has looked into the effects, and we though, that SetAmplify is from an old api, 

We had looked in pocketmine in entity‘s, there a 2 files. In the effect.php there a no amplify but in the effectinstance.php there it is that one.

https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/entity/Effect.php

https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/entity/EffectInstance.php

That errorcode is given, when /rg minigames effect 6 1 command would executed.

> Error: "Call to undefined method pocketmine\entity\Effect::setAmplifier()"

SetAmplifier is from an old api, you need do edit it and try with  effectinstance

An other plugin, used this  effects with effectistance. You could look at that you would given an hint, for your plugins

It could possible to help with the problem https://github.com/photoncodes/BlockEffects/tree/57c0ba4a3156166b1b66438689bea641f2efcad4/

**Comment by awgybop1** [comment]
Thank you! I will look into replacing the old API code with the newer one! :)

**Comment by suerion** [comment]
I think, the effects are going to work :) thanks a lot
