### ISSUE TITLE
Region not detecting

### ISSUE THREAD

**Issue by AbisGameryt** [Chalapa13/WorldGuard#107]
I created a region then when I try to set the flags it says region not found

**Comment by awgybop1** [comment]
More information is needed..
What command did you use to create the region and what command to set the flags?

**Comment by iZeaoGamer** [comment]
This is because you’ve entered the incorrect region. Please use your common sense before posting issues like this. Thank you.

**Comment by Chalapa13** [comment]
Insufficient information provided. But as @iZeaoGamer said you most likely entered an incorrect region.
