### ISSUE TITLE
TNT crash

### ISSUE THREAD

**Issue by minijaham** [Chalapa13/WorldGuard#108]
27.04 23:36:35 [Server] Server thread/CRITICAL TypeError: "Argument 1 passed to Chalapa13\WorldGuard\WorldGuard::getRegionByPlayer() must be an instance of pocketmine\Player, instance of pocketmine\entity\object\PrimedTNT given, called in phar:///plugins/WorldGuard.phar/src/Chalapa13/WorldGuard/EventListener.php on line 372" (EXCEPTION) in "plugins/WorldGuard.phar/src/Chalapa13/WorldGuard/WorldGuard" at line 198
27.04 23:36:35 [Server] Server thread/DEBUG #0 plugins/WorldGuard.phar/src/Chalapa13/WorldGuard/EventListener(372): Chalapa13\WorldGuard\WorldGuard->getRegionByPlayer(object pocketmine\entity\object\PrimedTNT)
27.04 23:36:35 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/MethodEventExecutor(42): Chalapa13\WorldGuard\EventListener->onHurtByEntity(object pocketmine\event\entity\EntityDamageByEntityEvent)
27.04 23:36:35 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object Chalapa13\WorldGuard\EventListener, object pocketmine\event\entity\EntityDamageByEntityEvent)
27.04 23:36:35 [Server] Server thread/DEBUG #3 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent)
27.04 23:36:35 [Server] Server thread/DEBUG #4 src/pocketmine/entity/Entity(925): pocketmine\event\Event->call()
27.04 23:36:35 [Server] Server thread/DEBUG #5 src/pocketmine/entity/Living(545): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
27.04 23:36:35 [Server] Server thread/DEBUG #6 src/pocketmine/Player(3708): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
27.04 23:36:35 [Server] Server thread/DEBUG #7 src/pocketmine/level/Explosion(200): pocketmine\Player->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
27.04 23:36:35 [Server] Server thread/DEBUG #8 src/pocketmine/entity/object/PrimedTNT(112): pocketmine\level\Explosion->explodeB()
27.04 23:36:35 [Server] Server thread/DEBUG #9 src/pocketmine/entity/object/PrimedTNT(97): pocketmine\entity\object\PrimedTNT->explode()
27.04 23:36:35 [Server] Server thread/DEBUG #10 src/pocketmine/entity/Entity(1383): pocketmine\entity\object\PrimedTNT->entityBaseTick(integer 1)
27.04 23:36:35 [Server] Server thread/DEBUG #11 src/pocketmine/level/Level(844): pocketmine\entity\Entity->onUpdate(integer 4050)
27.04 23:36:35 [Server] Server thread/DEBUG #12 src/pocketmine/level/Level(777): pocketmine\level\Level->actuallyDoTick(integer 4050)
27.04 23:36:35 [Server] Server thread/DEBUG #13 src/pocketmine/Server(2256): pocketmine\level\Level->doTick(integer 4050)
27.04 23:36:35 [Server] Server thread/DEBUG #14 src/pocketmine/Server(2387): pocketmine\Server->checkTickUpdates(integer 4050, double 1588030595.4336)
27.04 23:36:35 [Server] Server thread/DEBUG #15 src/pocketmine/Server(2143): pocketmine\Server->tick()
27.04 23:36:35 [Server] Server thread/DEBUG #16 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
27.04 23:36:35 [Server] Server thread/DEBUG #17 src/pocketmine/Server(1584): pocketmine\Server->start()
27.04 23:36:35 [Server] Server thread/DEBUG #18 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /, string[55] /plugins/)
27.04 23:36:35 [Server] Server thread/DEBUG #19 src/pocketmine/PocketMine(296): pocketmine\server()
27.04 23:36:35 [Server] Server thread/DEBUG #20 (11): require(string[107] phar:///PMMP-Latest-Stable.phar/sr)

**Comment by minijaham** [comment]
27.04 23:36:35 [Server] Server thread/EMERGENCY The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/4071481 or use the ID #4071481.

**Comment by awgybop1** [comment]
What version of WorldGuard?

**Comment by minijaham** [comment]
@awgybop1 v1.1.0.0

**Comment by minijaham** [comment]
I...probably got a wrong version?

**Comment by awgybop1** [comment]
Yes, that's why. This bug was fixed in the latest release (1.1.1.0) along with some additional fixes :)
