### ISSUE TITLE
Eating Flag

### ISSUE THREAD

**Issue by suerion** [Chalapa13/WorldGuard#109]
We had tried to take the eating flag and everytime he scrolls with the mous scroll, he could not do any food eating, but when he fly in creativ, he could eat.  The eating Flag was false. 

When he took the left click, on the mous and took the food from slot 1 to slot 3 or others, he could eat.

The region was from 0 to 255 blocks

**Comment by suerion** [comment]
I think, this is the „No Hunger“ flag

Here is an other plugin, what is work with „noHunger“ on the whole server

https://github.com/Matthww/NoHunger/blob/ab535b00686b2e8fd4302c6b230075ade29a1fbe/src/Matthww/NoHunger/NoHunger.php

**Comment by awgybop1** [comment]
Fixed :)

**Comment by suerion** [comment]
Thanks ;)
