### ISSUE TITLE
Creeper explosion

### ISSUE THREAD

**Issue by MrJhon2** [Chalapa13/WorldGuard#111]
Server thread/CRITICAL Error: "Call to a member function getName() on null" (EXCEPTION) in "plugins/WorldGuard.phar/src/Chalapa13/WorldGuard/WorldGuard" at line 246
08.05 04:47:34 [Server] Server thread/DEBUG #0 plugins/WorldGuard.phar/src/Chalapa13/WorldGuard/WorldGuard(236): Chalapa13\WorldGuard\WorldGuard->getRegionNameFromPosition(object pocketmine\level\Position)
08.05 04:47:34 [Server] Server thread/DEBUG #1 plugins/WorldGuard.phar/src/Chalapa13/WorldGuard/EventListener(390): Chalapa13\WorldGuard\WorldGuard->getRegionFromPosition(object pocketmine\level\Position)
08.05 04:47:34 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/MethodEventExecutor(42): Chalapa13\WorldGuard\EventListener->onHurt(object pocketmine\event\entity\EntityDamageByEntityEvent)
08.05 04:47:34 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object Chalapa13\WorldGuard\EventListener, object pocketmine\event\entity\EntityDamageByEntityEvent)
08.05 04:47:34 [Server] Server thread/DEBUG #4 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent)
08.05 04:47:34 [Server] Server thread/DEBUG #5 src/pocketmine/entity/Entity(925): pocketmine\event\Event->call()
08.05 04:47:34 [Server] Server thread/DEBUG #6 src/pocketmine/entity/Living(545): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
08.05 04:47:34 [Server] Server thread/DEBUG #7 src/pocketmine/Player(2588): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
08.05 04:47:34 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(150): pocketmine\Player->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
08.05 04:47:34 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(178): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
08.05 04:47:34 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
08.05 04:47:34 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/protocol/BatchPacket(126): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
08.05 04:47:34 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
08.05 04:47:34 [Server] Server thread/DEBUG #13 src/pocketmine/Player(3118): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
08.05 04:47:34 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
08.05 04:47:34 [Server] Server thread/DEBUG #15 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[20] 177.25.218.235 59091, object raklib\protocol\EncapsulatedPacket, integer 0)
08.05 04:47:34 [Server] Server thread/DEBUG #16 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
08.05 04:47:34 [Server] Server thread/DEBUG #17 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
08.05 04:47:34 [Server] Server thread/DEBUG #18 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
08.05 04:47:34 [Server] Server thread/DEBUG #19 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
08.05 04:47:34 [Server] Server thread/DEBUG #20 src/pocketmine/Server(2146): pocketmine\snooze\SleeperHandler->sleepUntil(double 1588927654.48)
08.05 04:47:34 [Server] Server thread/DEBUG #21 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
08.05 04:47:34 [Server] Server thread/DEBUG #22 src/pocketmine/Server(1584): pocketmine\Server->start()
08.05 04:47:34 [Server] Server thread/DEBUG #23 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[44] /, string[52] /plugins/)
08.05 04:47:34 [Server] Server thread/DEBUG #24 src/pocketmine/PocketMine(296): pocketmine\server()
08.05 04:47:34 [Server] Server thread/DEBUG #25 (11): require(string[87] phar:///jar/PocketMine1.14.phar/src/pocketmine/PocketM)

**Comment by awgybop1** [comment]
Thanks for the report! Unfortunately I was not able to replicate your issue after testing. If you still have this issue on the latest version, please contact us on Discord to have your issue directly taken care of.

Thank You!
