### ISSUE TITLE
Server closed when a TNT is about to explode

### ISSUE THREAD

**Issue by gidskie** [Chalapa13/WorldGuard#127]
PocketMine-MP Crash Dump Fri May 29 04:43:04 UTC 2020

Error: Argument 1 passed to Chalapa13\WorldGuard\WorldGuard::getRegionByPlayer() must be an instance of pocketmine\Player, instance of pocketmine\entity\object\PrimedTNT given, called in phar:///home/container/plugins/WorldGuard.phar/src/Chalapa13/WorldGuard/EventListener.php on line 372
File: plugins/WorldGuard.phar/src/Chalapa13/WorldGuard/WorldGuard
Line: 198
Type: TypeError

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: WorldGuard v1.1.0

Code:
[189]     public function onDisable(){
[190]         $this->saveRegions();
[191]     }
[192] 
[193]     public function getRegion(string $region)
[194]     {
[195]         return $this->regions[$region] ?? "";
[196]     }
[197] 
[198]     public function getRegionByPlayer(Player $player)
[199]     {
[200]         $reg = $this->getRegionOf($player);
[201]         return $reg !== "" ? $this->getRegion($reg) : "";
[202]     }
[203] 
[204]     public function getRegionOf(Player $player): string
[205]     {
[206]         return $this->players[$player->getRawUniqueId()] ?? "";
[207]     }
[208] 

Backtrace:
#0 plugins/WorldGuard.phar/src/Chalapa13/WorldGuard/EventListener(372): Chalapa13\WorldGuard\WorldGuard->getRegionByPlayer(object pocketmine\entity\object\PrimedTNT)
#1 src/pocketmine/plugin/MethodEventExecutor(42): Chalapa13\WorldGuard\EventListener->onHurtByEntity(object pocketmine\event\entity\EntityDamageByEntityEvent)
#2 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object Chalapa13\WorldGuard\EventListener, object pocketmine\event\entity\EntityDamageByEntityEvent)
#3 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent)
#4 src/pocketmine/entity/Entity(929): pocketmine\event\Event->call()
#5 src/pocketmine/entity/Living(545): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
#6 src/pocketmine/Player(3711): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
#7 src/pocketmine/level/Explosion(200): pocketmine\Player->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
#8 src/pocketmine/entity/object/PrimedTNT(112): pocketmine\level\Explosion->explodeB()
#9 src/pocketmine/entity/object/PrimedTNT(97): pocketmine\entity\object\PrimedTNT->explode()
#10 src/pocketmine/entity/Entity(1387): pocketmine\entity\object\PrimedTNT->entityBaseTick(integer 1)
#11 src/pocketmine/level/Level(844): pocketmine\entity\Entity->onUpdate(integer 16389)
#12 src/pocketmine/level/Level(777): pocketmine\level\Level->actuallyDoTick(integer 16389)
#13 src/pocketmine/Server(2256): pocketmine\level\Level->doTick(integer 16389)
#14 src/pocketmine/Server(2387): pocketmine\Server->checkTickUpdates(integer 16389, double 1590727384.7997)
#15 src/pocketmine/Server(2143): pocketmine\Server->tick()
#16 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
#17 src/pocketmine/Server(1584): pocketmine\Server->start()
#18 src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
#19 src/pocketmine/PocketMine(295): pocketmine\server()
#20 (11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by awgybop1** [comment]
Hello! This was fixed in the latest beta, along with many new added features.
https://poggit.pmmp.io/r/89335/WorldGuard_dev-154.phar
