### ISSUE TITLE
Can't build in protected areas even with perms

### ISSUE THREAD

**Issue by HyoukaKu** [Chalapa13/WorldGuard#144]
**EDIT:**
**The bug is fixed**
Thanks to Suerion who spent hours with me trying to find out what is the issue now i know whats the issue
Bypass permission is not added in the plugin code
The actual permission is
**For building ** worldguard.block-place.<region_name>
Example: worldguard.block-place.Spawn
**For breaking blocks** worldguard.break.<region_name>
Example: worldguard.break.Spawn
**Note** please keep in mind to write the lowercase letters and caps right
Also with spawn protection=-1

Also put perms for each world if you had multi worlds. And this was tested with 
""enable-multiworld-perms: true""
In pureperms config.yml file

**Describing the bug**
So when i give permissions to a rank using pureperms. worldguard.build players cant build when i take the op perm from them
Altho that i gave them the building perm

1. Make sure your pureperms is working without per world permission
""enable-multiworld-perms: false""
2. Open your pocketmine server
3. Setgperm or setuperm <player> worldguard.build
4. Deop yourself and try building in the protected area

You will see a message from worldguard plugin telling you that you cant build in this area

A Screenshot

![Screenshot_20200612-131143](https://user-images.githubusercontent.com/66826251/84492261-97d7a300-acae-11ea-9da7-beab27b75b2e.png)

![Screenshot_20200612-131235](https://user-images.githubusercontent.com/66826251/84492285-a1f9a180-acae-11ea-9bc8-0d3b81f7f784.png)

As you can see. I have pocketminw permission to bypass spawn protection
But the message is by worldguard

 - OS: [Android]
 - Browser [chrome]
 - Version [] not sure verison of what
But i have the latest few days ago update of the plugin

 - Device: Samsung grand prime +[]
 - OS: [Android 6.0.0 marshmallow]
 - Browser [i use chrome]
 - Version [dk that]

**Additional context**
I dont have latest pocketmine verison since it crashed the server from tnt usage
I have pocketmine ver3.12.0. For mcpe 1.14.60

**Comment by suerion** [comment]
Do you use Multiworld?

**Comment by suerion** [comment]
Please Give us an reproducing way, how You set up the perms and if you had reloaded with /ppreload after setting? Do you use multiworld?

**Comment by HyoukaKu** [comment]
I seted up the perms ingame using /setgperm {group_name} worldguard.build
And i tried /ppreload
I set my rank as the testing rank that i seted it up with the worldguard.build permission 
Yes i use MultiWorld plugin
I dont use op rank just a random testing rank. Yes i set myself with the testing rank then deop myself to test out permissions

**Comment by suerion** [comment]
https://github.com/Chalapa13/WorldGuard/wiki/Tutorial

worldguard.build-bypass.<REGION_NAME>: Allows building in region <REGION_NAME>
worldguard.break-bypass.<REGION_NAME>: Allows block breaking in region


Pureperms had an problem with multiword, if you need some help, please come in discord, i will help you with the problem.

**Comment by HyoukaKu** [comment]
Thanks alot

**Comment by awgybop1** [comment]
@HyoukaKu Is this problem still happening?

**Comment by HyoukaKu** [comment]
Yes i was just about to discuss suerion the issue again

**Comment by suerion** [comment]
Sorry @HyoukaKu we had found an Bug, i will check this

**Comment by suerion** [comment]
fixed in the next update ;)
