### ISSUE TITLE
flame bows work in protected areas

### ISSUE THREAD

**Issue by jaylac2000** [Chalapa13/WorldGuard#148]
even with pvp off

**Comment by suerion** [comment]
What version do you have?

**Comment by jaylac2000** [comment]
1.1.0

**Comment by suerion** [comment]
please try the newest dev phar file 
[WorldGuard_v1.1.6.1.zip](https://github.com/Chalapa13/WorldGuard/files/4775132/WorldGuard_v1.1.6.1.zip)

**Comment by jaylac2000** [comment]
will try it, thanks

**Comment by suerion** [comment]
is there already a problem? if not, i will close the issue
