### ISSUE TITLE
When Player get damaged by Mob

### ISSUE THREAD

**Issue by D7oomy1070** [Chalapa13/WorldGuard#153]
Server crashes when player get damaged by a monster.

**Expected behavior**
player should get damaged without server crash!

**Screenshots**
https://youtu.be/CePYm7_sfaI

 - OS: [Linux Ubuntu]
 - Browser [Firefox]
 - Version [1.1.0]

crash dump file
[Wed_Jun_17-21.39.30-+03_2020.log](https://github.com/Chalapa13/WorldGuard/files/4794566/Wed_Jun_17-21.39.30-%2B03_2020.log)

**Comment by suerion** [comment]
Is already fixed, please download on poggit ci

https://poggit.pmmp.io/ci/Chalapa13/WorldGuard the latest phar.

but, attention, copy your regions file and the others, and then delete it.

**Comment by D7oomy1070** [comment]
Oh when i tryed the latest dev phar file v(1.1.6.1) its just works fine !! **Thank you**.

**Comment by D7oomy1070** [comment]
The exact same problem with the same error message happens with " Ultimate boss plugin " !!
https://github.com/HmmHmmmm/BossPlugin

**Comment by suerion** [comment]
Does the error come without this problem?

Please send us the error code

**Comment by D7oomy1070** [comment]
Sorry !! my bad . i was using v1.1.6.1 not the latest which is v1.1.6.3 it's working perfectly without any errors thanks so much for the super fast response !!

**Comment by suerion** [comment]
Is it working without Boss Plugin?

Could you send us your error code please

**Comment by D7oomy1070** [comment]
this time i think it's a PureEntitiesX problem not a world guard but anyways this is the crash dump file:
[Fri_Jun_19-20.31.42-+03_2020.log](https://github.com/Chalapa13/WorldGuard/files/4805999/Fri_Jun_19-20.31.42-%2B03_2020.log)

**Comment by suerion** [comment]
This has nothing to do with WorldGuard:

BAD PLUGIN: PureEntitiesX v0.6.6
