### ISSUE TITLE
BossPlugin

### ISSUE THREAD

**Issue by TWRRR** [Chalapa13/WorldGuard#155]
**Describe the bug**
When A Boss From The plugin BossPlugin deals damage to a player, the entire server crashes.

**To Reproduce**
1. Get bossplugin
2. Spawn A Boss
3. Get hit by the boss

**Comment by awgybop1** [comment]
Happens with and without WorldGuard, please contact the developer of the plugin as this is not an issue with WorldGuard as far as I see.

**Comment by Chalapa13** [comment]
As @awgybop1 said this is not a problem caused by WorldGuard
