### ISSUE TITLE
Incorrect protection (Latest version pocketmine and the plugin)

### ISSUE THREAD

**Issue by UnEnanoMas** [Chalapa13/WorldGuard#156]
**Describe the bug**
I put 2 positions when I create a new region, and I do not enable it to protect the blocks above or below, only the marked area.

Well it does not work, it protects the bottom and top ones from the marked position.

**To Reproduce**
1. Create a new region
2. Mark the 2 positions (Example 70 100 50 and 35 105 25)
3. Now remove the op and restart the server, and try to break the blocks below or above
4. You will see how it puts you that it is protected when it should not be

**Expected behavior**
Should protect the marked area at the marked height.

**Screenshots**
![Captura de pantalla (110)](https://user-images.githubusercontent.com/63286108/86601863-27b4f800-bfa2-11ea-9d5c-e2ad1b809ea4.png)
![Captura de pantalla (111)](https://user-images.githubusercontent.com/63286108/86601882-2c79ac00-bfa2-11ea-99d0-d2f81e52d1f6.png)

I have translated the plugin into Spanish, what it says is that I cannot break blocks in that region, when the height of the block is less than the protection that I have put (And do not enable it to be protected from top to bottom)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: OperaGX
 - Version: Dont know

**Comment by suerion** [comment]
In the Config is allways Block Breaking False, you need to bypass this with permission, or you set it on the config to true

**Comment by UnEnanoMas** [comment]
I say that it is protecting blocks that it should not protect, they do not enter the ratio that I put of protection

**Comment by suerion** [comment]
yeah, i had seen it, but i had also asked for your region.yml file

if you had created the region in the ui, could it be, you had probably switch it to 0 - 255?

**Comment by UnEnanoMas** [comment]
Prueba:
  pos1:
  - 1983
  - 0
  - 4267
  pos2:
  - 1993
  - 255
  - 4276
  level: Censored
  flags:
    block-place: "false"
    block-break: "false"
    pvp: "true"
    deny-msg: "true"
    console-cmd-on-enter: none
    console-cmd-on-leave: none
    flow: "true"
    exp-drops: "true"
    invincible: "false"
    fall-dmg: "true"
    effects: []
    blocked-cmds: []
    allowed-cmds: []
    use: "false"
    item-drop: "true"
    explosion: "false"
    notify-enter: ""
    notify-leave: ""
    potions: "true"
    allowed-enter: "true"
    allowed-leave: "true"
    game-mode: "false"
    sleep: "true"
    send-chat: "true"
    receive-chat: "true"
    enderpearl: "true"
    fly-mode: 0
    eat: "true"
    hunger: "true"
    allow-damage-animals: "true"
    allow-damage-monsters: "true"
    allow-leaves-decay: "true"
    allow-plant-growth: "true"
    allow-spreading: "true"
    allow-block-burn: "true"
    priority: 0
...

lol well if you have set from 0 to 255 without activating it

**Comment by suerion** [comment]
please set the y cords and try it again, i don't know whats your version, yet

it would b in the config, or you do /pl then it shows you all plugins

**Comment by UnEnanoMas** [comment]
Dev 178

**Comment by suerion** [comment]
yeah, we look on it

**Comment by suerion** [comment]
It works for me normaly

i don't could this reproduce

with 178 and with the newest dev file

you need to disable the option
