### ISSUE TITLE
tnt crash server 

### ISSUE THREAD

**Issue by NormalOcean6686** [Chalapa13/WorldGuard#160]
When lighting tnt is about to explode the server crashes

`

21:01:20 Server|CRITICAL > TypeError: "Argument 1 passed to Chalapa13\WorldGuard\WorldGuard::getRegionByPlayer() must be an instance of pocketmine\Player, instance of pocketmine\entity\object\PrimedTNT given, called in phar:///home/container/plugins/WorldGuard.phar/src/Chalapa13/WorldGuard/EventListener.php on line 372" (EXCEPTION) in "plugins/WorldGuard.phar/src/Chalapa13/WorldGuard/WorldGuard" at line 198

21:01:20 Server|DEBUG > #0 plugins/WorldGuard.phar/src/Chalapa13/WorldGuard/EventListener(372): Chalapa13\WorldGuard\WorldGuard->getRegionByPlayer(object pocketmine\entity\object\PrimedTNT)

21:01:20 Server|DEBUG > #1 src/pocketmine/plugin/MethodEventExecutor(42): Chalapa13\WorldGuard\EventListener->onHurtByEntity(object pocketmine\event\entity\EntityDamageByEntityEvent)

21:01:20 Server|DEBUG > #2 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object Chalapa13\WorldGuard\EventListener, object pocketmine\event\entity\EntityDamageByEntityEvent)

21:01:20 Server|DEBUG > #3 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent)

21:01:20 Server|DEBUG > #4 src/pocketmine/entity/Entity(1169): pocketmine\event\Event->call()

21:01:20 Server|DEBUG > #5 src/pocketmine/entity/Living(672): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)

21:01:20 Server|DEBUG > #6 src/pocketmine/Player(4144): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)

21:01:20 Server|DEBUG > #7 src/pocketmine/level/Explosion(204): pocketmine\Player->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)

21:01:20 Server|DEBUG > #8 src/pocketmine/entity/object/PrimedTNT(112): pocketmine\level\Explosion->explodeB()

21:01:20 Server|DEBUG > #9 src/pocketmine/entity/object/PrimedTNT(97): pocketmine\entity\object\PrimedTNT->explode()

21:01:20 Server|DEBUG > #10 src/pocketmine/entity/Entity(1711): pocketmine\entity\object\PrimedTNT->entityBaseTick(integer 1)

21:01:20 Server|DEBUG > #11 src/pocketmine/level/Level(906): pocketmine\entity\Entity->onUpdate(integer 1072)

21:01:20 Server|DEBUG > #12 src/pocketmine/level/Level(834): pocketmine\level\Level->actuallyDoTick(integer 1072)

21:01:20 Server|DEBUG > #13 src/pocketmine/Server(2370): pocketmine\level\Level->doTick(integer 1072)

21:01:20 Server|DEBUG > #14 src/pocketmine/Server(2493): pocketmine\Server->checkTickUpdates(integer 1072, double 1595019679.9629)

21:01:20 Server|DEBUG > #15 src/pocketmine/Server(2261): pocketmine\Server->tick()

21:01:20 Server|DEBUG > #16 src/pocketmine/Server(2104): pocketmine\Server->tickProcessor()

21:01:20 Server|DEBUG > #17 src/pocketmine/Server(1691): pocketmine\Server->start()

21:01:20 Server|DEBUG > #18 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)

21:01:20 Server|DEBUG > #19 src/pocketmine/PocketMine(304): pocketmine\server()

21:01:20 Server|DEBUG > #20 (11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
`

**Comment by suerion** [comment]
Please use the last release from dev poggit


https://poggit.pmmp.io/ci/Chalapa13/WorldGuard/WorldGuard

1.1.6-4

**Comment by NormalOcean6686** [comment]
Ok thanks
