### ISSUE TITLE
Blocks can be broken?

### ISSUE THREAD

**Issue by AyanKR** [Chalapa13/WorldGuard#21]
I am quite sure i have done everything required to setup the region but when a normal player breaks the block it shows "You cannot break blocks in this region" but the block breaks?

**Comment by AyanKR** [comment]
Also this error shows up in the console  Server thread/CRITICAL "Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'WorldGuard v1': Return value of WorldGuard\Region::getEffects() must be of the type array, null returned on WorldGuard\EventListener
25.08 07:14:55 [Server] Server thread/CRITICAL TypeError: "Return value of WorldGuard\Region::getEffects() must be of the type array, null returned" (EXCEPTION) in "/WorldGuard_v1.phar/src/WorldGuard/Region" at line 240

**Comment by MasterOfTheRealm** [comment]
Which version of PMMP?

**Comment by optimusprime338** [comment]
it works fine in genisys

**Comment by Muqsit** [comment]
https://github.com/Muqsit/WorldGuard/commit/1b2c9922e1e4fd5682c1c3d702bbe58397e5a943
