### ISSUE TITLE
Error Fly?

### ISSUE THREAD

**Issue by NycuRO** [Chalapa13/WorldGuard#30]
![image](https://user-images.githubusercontent.com/13573011/32573413-98de974e-c4d6-11e7-87bf-450b4883ab01.png)

I'm exit from protection and fly works. Wtf? @Muqsit

**Comment by Muqsit** [comment]
https://github.com/Muqsit/WorldGuard/commit/1b2c9922e1e4fd5682c1c3d702bbe58397e5a943

**Comment by Muqsit** [comment]
The rewrite branch is still not suitable for production though, let this issue be open so no one else creates a duplicate of it

**Comment by NycuRO** [comment]
Ok muqy 🗡

**Comment by awgybop1** [comment]
Just checked and I had no problems. Make sure the value of "fly-mode" is set to "3", this will enable Flight while in the region and disable it when you leave.
