### ISSUE TITLE
Possible adding of per group to a allowed-entry false location

### ISSUE THREAD

**Issue by jbreadtoasted** [Chalapa13/WorldGuard#35]
I would like to be able to allow certain ranks to enter certain areas fo example, Entering the vip shop will be for vips only not anyone else and the ones who dont have the permision for that specific region such as a permission like this wg.regionname.rankgroupname.bypass that would allow them to only bypass and go into that area for the vips only but wouldnt allow them to go into the owner region if you get what im saying.

**Comment by jbreadtoasted** [comment]
Can anyone start work on this? I would really love to have this feature @Muqsit

**Comment by Chalapa13** [comment]
@jbreadtoasted Altough maybe late, I added the functionality you requested. I just took over what @Muqsit started and I'm adding a lot of new features and keeping the plugin up to date. Hope you will find those features usefull. Let me know if it works as you requested and also feel free to suggest more features to be added. (Check the tutorial for examples of your request)
