### ISSUE TITLE
Editable Flag and Perms broken

### ISSUE THREAD

**Issue by RealGroot** [Chalapa13/WorldGuard#45]
So in every version past dev build 19 the editable flag doesnt work at all, and in version 19 the flag works but i cant set another region editable inside the non editable region meaning i cant protect my prison and let people mine the mines at the same time.... please fix this add me on discord for help troubleshooting its MoonDoggie#7777

**Comment by Chalapa13** [comment]
There is no longer a flag called `editable` only the `worldguard.edit` perm. I contacted you on your discord about this issue. After your confirmation that the problem is solved I will close this issue.
