### ISSUE TITLE
Support sub-region flag overrides.

### ISSUE THREAD

**Issue by kabluinc** [Chalapa13/WorldGuard#5]
Please can you add a feature to this plugin where you can overlap lands and allow smaller regions within a large region to be unprotected or editable by whitelisted players. It would work like you could protect a whole house so that people cant break or place. Then you could create another region covering a room in the house which is editable. The region of the room would bypass the region that covers the whole house. 

Its hard to explain but in simple words, the ability to create a large protected area and then define a small unprotected are inside it. This would allow you to protect a large area like a city and only create un protected regions or whitelisted regions within that area

**Comment by Muqsit** [comment]
This might be kind of confusing to code..

**Comment by Muqsit** [comment]
https://github.com/Muqsit/WorldGuard/commit/1b2c9922e1e4fd5682c1c3d702bbe58397e5a943

**Comment by Chalapa13** [comment]
Feature has been now implemented and documented in the tutorial. Please open a new issue if you are having problems with this feature.
