### ISSUE TITLE
Spam?

### ISSUE THREAD

**Issue by KingRainbow44** [Chalapa13/WorldGuard#52]
So. Everytime I hit a player, I get a responce of,

[04:53:15] [Server thread/NOTICE]: [WorldGuard] pocketmine\Player

What is going on?

**Comment by Chalapa13** [comment]
I am going to need the full error log in order to determine what issue you are experiencing @KingRainbow44

**Comment by KingRainbow44** [comment]
There is no error. It's just that everything an entity, a message of something like that appears.

**Comment by Chalapa13** [comment]
Oh that is for debugging, I will disable it
