### ISSUE TITLE
blocking commads

### ISSUE THREAD

**Issue by Play2KillTV** [Chalapa13/WorldGuard#61]
when blocking a command it sends this error:
Error: "Call to undefined function Chalapa13\WorldGuard\saveRegions()" (EXCEPTION) in "plugins/WorldGuard-master/src/Chalapa13/WorldGuard/WorldGuard" at line 602

line 602:
 saveRegions();

It still blocks the command but it throws an error.

**Comment by Chalapa13** [comment]
I fixed the issue in the latest commit. Please download that dev build.
