### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jennocool** [Chalapa13/WorldGuard#66]
I had regions when I had te plugin.
When I deleted Plugin the region is sort of still excisting I can't pvp in some areas how to fix this it is ruining my server

**Comment by awgybop1** [comment]
Hello, please make sure that you've deleted the plugin from your **/plugins** directory. If you've already done this and rebooted your server, the plugin is removed. If you still experience issues after removing and rebooting, it is something else inside your server.
