### ISSUE TITLE
Bug with player effects

### ISSUE THREAD

**Issue by TetroYT** [Chalapa13/WorldGuard#86]
i havent tested its because the effects are coming from a custom enchant (it is still a vanilla effect)
but when players leave areas the effects disappear from them and they have to take off their armour and put it back on, also can you add a flag where players can still take damage from entitys if pvp is turned off this will be useful for my bosses warp where i want players to be able to take damage from entitys and give damage to entitys but not be able to deal damage to other players

**Comment by awgybop1** [comment]
Not sure about the first one, that shouldn't be related to WorldGuard as it doesn't remove any effects that aren't infinite.
I will also add your suggestion into the plugin ASAP!
