### ISSUE TITLE
i cant seem to add effects to a region

### ISSUE THREAD

**Issue by jaylac2000** [Chalapa13/WorldGuard#87]
[Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\entity\Effect::setAmplifier()" (EXCEPTION) in "plugins/WorldGuard.phar/src/Chalapa13/WorldGuard/Region" at line 129

**Comment by awgybop1** [comment]
Effects are currently not working due to some issues with PocketMine. We will get them ready ASAP!
