### ISSUE TITLE
A Few Bugs

### ISSUE THREAD

**Issue by pleasepoggitwork** [Chalapa13/WorldGuard#93]
1. Lava/Water can flow into protected areas, and form cobblestone, making it possible to greif protected areas
2. Effects from PiggyCES, Remove when you switch regions
3. Players can place lava/water in spawn

**Comment by awgybop1** [comment]
Will fix :)

**Comment by pleasepoggitwork** [comment]
Actually lava/water cant be placed when use = false. Ive made a custom worldguard version to remove all effects, but you could make the effects from worldguard last longer than piggyce effects, Then just make the plugin remove any effects higher than worldguard's effects, but not piggyces. The first one is still broken though.

**Comment by awgybop1** [comment]
Okay, I'll make sure it's not restricted to the use flag however - as it should be part of the block place flag
null

**Comment by awgybop1** [comment]
Fixed, Fixed, and... Fixed!
