### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Johnsonk79** [Chalapa13/WorldGuard#95]
I know this bug is in the to-do list, but please fix it as soon as you can, with it registering 1 right-click as 2, I literally cannot create any regions using my computer :(

**Comment by awgybop1** [comment]
Hello! I can get this fixed, but it's not actually a bug, it's just how the PC version does it, sometimes it registers 2 clicks. For right now just try to be very careful

**Comment by Johnsonk79** [comment]
I figured out a solution for this, you can actually place down an interactive block such as a trapdoor and use it to register the locations, then it will only register as 1 single right-click.

I try to do it as carefully as I can but as long as its a full block there is no way for it to register only 1 right-click.
