### ISSUE TITLE
PVP Bug

### ISSUE THREAD

**Issue by Johnsonk79** [Chalapa13/WorldGuard#96]
This was not an issue a while ago, but after I update the plugin, even if the pvp flag is set to true players cannot pvp and will get the **You cannot hurt players in this region** message.

Just another suggestion, please add gamemode adventure to the game-mode flag

Thanks a lot :)

**Comment by awgybop1** [comment]
Could not reproduce the issue, please join our Discord and message me for further help :)

And I added the Adventure game-mode 👍
