### ISSUE TITLE
Gamemode Bug

### ISSUE THREAD

**Issue by suerion** [Chalapa13/WorldGuard#97]
Hello, i had added some Regions with Gamemode changing, when player (we had tested it with 6 other chars) get into the region or spawn to this region, it doesnt change the Gamemode.

We tested it with more Regions and more World, it neither changed the gamemode.

We had added all permissions an inserted all regions with pureperm. pvp, chest, doors are work correctly...

Please look at it. 

when you need some informations about our server properties, let me know.

**Comment by nomadjimbob** [comment]
I am having the same issue. PocketMine 3.11.7, WorldGuard 1.1.0

**Comment by awgybop1** [comment]
Were you OPs or did you have the gamemode bypass permission? Gamemode only affects normal players

**Comment by suerion** [comment]
Yes i‘m the only one with gamemode bypass and op, but the other has not this permissions, i looked at the groups a lot of times for this, but the other groups don‘t has the bypass.  I have checked it 3 or more times.

alsoe, the test chars are not op and doesn‘t have the bypass in the permission.

**Comment by suerion** [comment]
`Kinder:
  alias: knd
  isDefault: true
  inheritance: []
  permissions: []
  worlds:
    Plotwelt:
      isDefault: true
      permissions:
      - essentialstp.command.bedsetshome
      - essentialstp.command.delhome
      - essentialstp.command.home
      - essentialstp.command.sethome
      - essentialstp.command.spawn
      - essentialstp.command.tpa
      - essentialstp.command.tpaccept
      - essentialstp.command.tpahere
      - essentialstp.command.tpdeny
      - essentialstp.command.warp
      - myplot.claimplots.4
      - myplot.command.add
      - myplot.command.auto
      - myplot.command.biome
      - myplot.command.clear
      - myplot.command.denyplayer
      - myplot.command.dispose
      - myplot.command.home
      - myplot.command.info
      - myplot.command.list
      - myplot.command.middle
      - myplot.command.name
      - myplot.command.remove
      - myplot.command.undenyplayer
      - portal.minigames
      - worldguard.enter.Plotwelt
      - worldguard.leave.Plotwelt
    Minigames:
      isDefault: true
      permissions:
      - essentialstp.command.bedsetshome
      - essentialstp.command.delhome
      - essentialstp.command.home
      - essentialstp.command.sethome
      - essentialstp.command.spawn
      - essentialstp.command.tpa
      - essentialstp.command.tpaccept
      - essentialstp.command.tpahere
      - essentialstp.command.tpdeny
      - essentialstp.command.warp
      - portal.plotwelt
      - portal.skyblock
      - portal.skywars
      - worldguard.enter.Minigames
      - worldguard.leave.Minigames
    Projekte:
      isDefault: true
      permissions: []
    SkyWars:
      isDefault: true
      permissions:
      - portal.swplotwelt
      - sw.cmd.help
      - sw.cmd.join
      - sw.cmd.leave
      - sw.cmd.shop
      - worldguard.enter.Skywars
      - worldguard.leave.Skywars
    SkyBlock:
      isDefault: true
      permissions:
      - essentialstp.command.bedsetshome
      - essentialstp.command.delhome
      - essentialstp.command.home
      - essentialstp.command.sethome
      - essentialstp.command.spawn
      - essentialstp.command.tpa
      - essentialstp.command.tpaccept
      - essentialstp.command.tpahere
      - essentialstp.command.tpdeny
      - essentialstp.command.warp
      - portal.sbplotwelt
      - skyblock.interaction
      - worldguard.enter.Skyblock
      - worldguard.leave.Skyblock`

**Comment by suerion** [comment]
This are the Permissions from the Group
 https://hastebin.com/cohonodiha.css

And this is from Worldguard
https://hastebin.com/falepexuwo.sql

But, my char is always in adventure mode, i don't have gave him this mode yet

**Comment by suerion** [comment]
@awgybop1 
https://youtu.be/VNSqUeixXGI

I had changed worlds, 

I think, the regions detection is not right.

Thanks

**Comment by awgybop1** [comment]
Fixed!
