### ISSUE TITLE
Global region is not applied when leaving defined region

### ISSUE THREAD

**Issue by nomadjimbob** [Chalapa13/WorldGuard#98]
When a player leaves a defined region and enters an area that is not defined, the global region flags are not applied.

The rough fix (I think) would be to add the following to getRegionNameFromPosition()

```
// Check if global region overrides current region
if(isset($this->regions['global.'.$pos->getLevel()->getName()])) {
    if($highestPriority<intval($region->getFlag("priority"))) {
        $highestPriorityName = 'global.'.$pos->getLevel()->getName();
        $highestPriority = intval($region->getFlag("priority"));
    }
}
```

Not sure if ignoring global regions in getRegionNameFromPosition() is by design

**Comment by nomadjimbob** [comment]
I understand @awgybop1. The issue stems in:

```
public function onRegionChange(Player $player, string $oldregion, string $newregion)
{
    $new = $this->getRegion($newregion);
    $old = $this->getRegion($oldregion);
    …
```

**Comment by awgybop1** [comment]
No, this is NOT how Global Regions work. Global regions work by detecting if you're not in a defined region. If you're not, it then checks if a global region exists for that world and if so applies the flags. For now those are limited to block break, block place, pvp, fall damage, and invincibility.

**Comment by nomadjimbob** [comment]
OK. So changing a worlds game-mode in a region will always require an enveloping region to restore the worlds game-mode?

**Comment by awgybop1** [comment]
Sorry, I did not understand what you were asking at first.
Your suggestion makes a lot of sense - instead of adding a check to every flag, add the check to the GetRegionByName() and return the global region if it exists for that world - and immediately every flag will work.

**Comment by awgybop1** [comment]
Issue Fixed. Global region is now a part of the GetRegionNameFromPosition and works with all flags.

**Comment by Johnsonk79** [comment]
How do you create a global region?

**Comment by nomadjimbob** [comment]
@Johnsonk79 The Discord channel is probably a better place to ask for support. Global regions are mentioned on the wiki - https://github.com/Chalapa13/WorldGuard/wiki/Tutorial#creating-global-regions
